# Generated by Django 5.2.6 on 2026-07-24 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_organizationmember'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationmember',
            name='role',
            field=models.CharField(choices=[('OWNER', 'Owner'), ('ADMIN', 'Admin'), ('PROJECT_MANAGER', 'Project Manager'), ('DEVELOPER', 'Developer'), ('CLIENT', 'Client'), ('TEAMLEAD', 'TeamLead')], default='DEVELOPER', max_length=30),
        ),
    ]
