# Generated by Django 5.2.6 on 2026-07-24 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0003_alter_organizationmember_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organizationmember",
            name="role",
            field=models.CharField(
                choices=[
                    ("OWNER", "Owner"),
                    ("ADMIN", "Admin"),
                    ("PROJECT_MANAGER", "Project Manager"),
                    ("DEVELOPER", "Developer"),
                    ("CLIENT", "Client"),
                    ("TEAMLEAD", "TeamLead"),
                    ("QA", "Qa"),
                ],
                default="DEVELOPER",
                max_length=30,
            ),
        ),
    ]
